### ISSUE TITLE
プレイリストのすべての曲をキューに追加してほしい

### ISSUE THREAD

**Issue by yoheiuc** [sakkuntyo/discord-sktrythmjs#2]
プレイリストの URL をキューに登録したら、そのプレイリストの曲すべてをキューに登録する機能を実装してください

**Comment by sakkuntyo** [comment]
https://stackoverflow.com/questions/62981694/download-youtube-playlist
ここを参考にするとytplを使えばできそう
出来たら実装します

**Comment by sakkuntyo** [comment]
対応しました。
07f7eacef9ab19939931f43603b4d0a0c126e40a
